platform: linux/amd64

pipeline:
  job-docker-dind:
    image: docker:dind
    commands:
      - sleep 10 # give docker enough time to start
      - docker run --rm hello-world

services:
  docker:
    image: docker:dind
    privileged: true
