platform: linux/amd64

# Define a temporary volume for communicating with the DIND service.
.dockervol: &dockervol
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

pipeline:
  job-docker:
    image: docker:dind
    commands:
      - docker run --rm hello-world
    # Needs 'trusted' privileges
    <<: *dockervol
