platform: lxc

pipeline:
  job-lxc:
    image: debian:bullseye
    commands:
      # Set up Docker
      - apt-get install -yq ca-certificates curl gnupg lsb-release
      - mkdir -p /etc/apt/keyrings
      - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      # "Fixes" wrong Debian security update site in apt config
      - "apt-get update ||:"
      - apt-get install -yq docker-ce docker-ce-cli containerd.io docker-compose-plugin
      # Finally run Docker hello-world
      - docker run --rm hello-world
